nelmio_api_doc:
    documentation:
        info:
            title: Chatbot API
            description: Chatbot API documentation
            version: 1.0.0
    areas:
        path_patterns: [ ^/api ]